name: mak_dairy
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.6
  datetime_picker_formfield_new: ^2.1.0
  image_picker: ^1.0.4
  image_cropper: ^5.0.0
  dio: ^5.3.4
  pdf: ^3.10.6
  connectivity_plus: ^5.0.2
  path_provider: ^2.1.1
  flutter_pdfview: ^1.3.2
  open_file: ^3.3.2
  share_plus: ^7.2.1

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Regular.ttf
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
